export const feedData = [
  {
    id: 1,
    author: 'Eleanor Voss',
    avatar: 'EV',
    avatarColor: '#7c3aed',
    role: 'Author',
    time: '2 min ago',
    type: 'milestone',
    content:
      "Just completed Chapter 12 of 'The Infinite Cartographer'! 🎉 The AI draft assistant helped me break through my writer's block — the pacing suggestions were spot on. Now heading into the climax arc.",
    tags: ['Fantasy', 'Draft Complete'],
    likes: 48,
    comments: 12,
    liked: false,
    bookTitle: 'The Infinite Cartographer',
    progress: 75,
    coverColor: 'violet',
    progressFrom: '#7c3aed',
    progressTo: '#4f46e5',
  },
  {
    id: 2,
    author: 'Marcus Aldren',
    avatar: 'MA',
    avatarColor: '#059669',
    role: 'Editor',
    time: '18 min ago',
    type: 'editorial',
    content:
      "Completed developmental editing on 'Synthetic Shores' by @priyak. The manuscript's structural tension is excellent — flagged 3 pacing issues in Act II and suggested subplot expansion for Chapter 8. Manuscript delivered. \u2705",
    tags: ['Dev Edit', 'Delivered'],
    likes: 31,
    comments: 7,
    liked: true,
    bookTitle: 'Synthetic Shores',
    coverColor: 'emerald',
    progressFrom: '#059669',
    progressTo: '#0d9488',
  },
  {
    id: 3,
    author: 'Priya Krishnan',
    avatar: 'PK',
    avatarColor: '#ea580c',
    role: 'Author',
    time: '1 hr ago',
    type: 'cover',
    content:
      "Look what the AI Cover Generator produced for my sci-fi novel! I gave it the theme 'ocean meets code' and it nailed the mood. Tweaked the typography a bit \u2014 what do you all think?",
    tags: ['Cover Design', 'Sci-Fi'],
    likes: 93,
    comments: 24,
    liked: false,
    bookTitle: 'Synthetic Shores',
    coverColor: 'cyan',
    hasCoverPreview: true,
  },
  {
    id: 4,
    author: 'Admin \u00b7 James Osei',
    avatar: 'JO',
    avatarColor: '#b45309',
    role: 'Admin',
    time: '3 hrs ago',
    type: 'announcement',
    content:
      "Platform Update: Plagiarism Detection v2.0 is now live! Accuracy has improved by 34%, and we've added cross-language detection support for 18 languages. Manuscripts already in review will be re-scanned automatically.",
    tags: ['Platform Update', 'Announcement'],
    likes: 120,
    comments: 38,
    liked: false,
    isAnnouncement: true,
  },
  {
    id: 5,
    author: 'Serena Holt',
    avatar: 'SH',
    avatarColor: '#7c3aed',
    role: 'Author',
    time: '5 hrs ago',
    type: 'review',
    content:
      'Received my proofread manuscript back from the editorial team. 847 annotations \u2014 meticulous work! The consistency check caught 14 character name discrepancies I never would have caught myself. This platform is something else.',
    tags: ['Proofreading', 'Review'],
    likes: 67,
    comments: 15,
    liked: true,
    bookTitle: 'Glass Atlas',
    coverColor: 'rose',
    progressFrom: '#e11d48',
    progressTo: '#ea580c',
  },
];